### PR TITLE
minimum googleplay support

### PR DESCRIPTION
**Pull request by Jonhyfun**
https://support.google.com/podcast-publishers/answer/9889544?hl=en

### CODE REVIEW

**Comment by bcomnes** [comment]
Oh cool, adding google play support would be awesome.

**Comment by bcomnes** [comment]
Before I land this, I need to audit derived data possibilities, updating docs, and adding a snapshot test to a feed with these fields. Reminder to myself.

**Review by bcomnes — CHANGES_REQUESTED** [review]
@jonhyfun Looks good, willing to land this, but can you undo the changes to package.json?  Not sure if it helps, but you can install forks in npm from GitHub branches by specifying `Jonhyfun/jsonfeed-to-rss#master` in the version field for `jsonfeed-to-rss` in your consuming package.json while you wait for upstream to land.  Slightly less work than scoped publishing, but either way works.

**Comment by digicommons** [comment]
Just stumbled upon this issue as I also had trouble with episode images not updating correctly ([ab14bb4](https://github.com/bcomnes/jsonfeed-to-rss/pull/28/commits/ab14bb495657f919b81bdb7f30e4ed71f1e8e504)).

Since the changes requested in this issue concern other parts of the code as well, would you mind if I open a separate pull request?

**Comment by bcomnes** [comment]
Yeah go for it

**Comment by bcomnes** [comment]
I never got around to looking into google play so if you wanted to finish up this pr, that's available to do.

**Comment by bcomnes** [comment]
Closing till someone has time for this. Open to this change.

**Pull request closed without merging**
